"use client";
import { useEffect,useState } from "react";
import { request } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Field,Panel } from "./shared";
type Challenge={challengeId:string;message:string;deliveryMode:string};
type SecurityStatus={verified:boolean;deliveryMode:string;verifiedAt?:string;activeSessions:number;emailConfigured:boolean};

export function AccountSecurity({auth,onClose,onSignedOut}:{auth:string;onClose:()=>void;onSignedOut:()=>void}) {
  const [status,setStatus]=useState<SecurityStatus>();const [challenge,setChallenge]=useState<Challenge>();const [code,setCode]=useState("");const [current,setCurrent]=useState("");const [password,setPassword]=useState("");const [repeat,setRepeat]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{let cancelled=false;void request<SecurityStatus>("account/security","GET",undefined,auth).then(s=>!cancelled&&setStatus(s)).catch(e=>!cancelled&&setError(e.message));return()=>{cancelled=true;};},[auth]);
  async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setMessage("");try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="fm-dialog fm-dialog-wide"><DialogHeader><DialogTitle>Account security</DialogTitle><DialogDescription>Manage your password, email verification and signed-in sessions.</DialogDescription></DialogHeader><div className="fm-dialog-body fs-form fs-security-body">
    {error&&<p role="alert" className="fm-error">{error}</p>}{message&&<p role="status">{message}</p>}
    <Panel title="Email verification"><p>{!status?"Loading email verification status...":status.verified?"Your email address is verified.":"Your email address has not been verified."}</p>{status&&!status.emailConfigured&&<p>Email delivery is not configured yet. Contact the platform owner to enable verification and recovery.</p>}{!status?.verified&&<Button disabled={busy||!status?.emailConfigured} onClick={()=>void run(async()=>{const c=await request<Challenge>("account/verification","POST",{},auth);setChallenge(c);setMessage(c.message);})}>Send verification code</Button>}{challenge&&<><Field label="Six-digit email code"><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/></Field><Button disabled={busy||code.length!==6} onClick={()=>void run(async()=>{await request("account/verification/confirm","POST",{challengeId:challenge.challengeId,code},auth);setStatus(await request<SecurityStatus>("account/security","GET",undefined,auth));setChallenge(undefined);setCode("");setMessage("Email verified.");})}>Confirm email</Button></>}</Panel>
    <Panel title="Change password"><form className="fs-form" onSubmit={e=>{e.preventDefault();void run(async()=>{if(password!==repeat)throw new Error("The new passwords do not match.");await request("account/password","POST",{currentPassword:current,newPassword:password},auth);onSignedOut();});}}><Field label="Current password"><Input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></Field><Field label="New password"><Input required minLength={10} maxLength={72} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></Field><Field label="Repeat new password"><Input required type="password" autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></Field><p>Changing your password signs out every session. Sign in again with your new password.</p><Button disabled={busy}>Change password</Button></form></Panel>
    <Panel title="Sessions"><p>{status?.activeSessions??"..."} active session(s). Tokens expire after one hour.</p><Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{await request("account/logout-all","POST",{},auth);onSignedOut();})}>Sign out all sessions</Button></Panel>
  </div></DialogContent></Dialog>;
}
export function PasswordRecovery({onClose}:{onClose:()=>void}) {
  const [identity,setIdentity]=useState("");const [challenge,setChallenge]=useState<Challenge>();const [code,setCode]=useState("");const [password,setPassword]=useState("");const [repeat,setRepeat]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [done,setDone]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{if(!challenge)setChallenge(await request<Challenge>("public/auth/recovery","POST",{identity}));else{if(password!==repeat)throw new Error("The passwords do not match.");await request("public/auth/reset","POST",{challengeId:challenge.challengeId,code,password});setDone(true);setPassword("");setRepeat("");}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="fm-dialog"><DialogHeader><DialogTitle>Recover your account</DialogTitle><DialogDescription>Use a one-time code sent to your registered email address.</DialogDescription></DialogHeader>{done?<><p>Password updated. All previous sessions are signed out.</p><Button onClick={onClose}>Return to sign in</Button></>:<form className="fs-form" onSubmit={submit}>{!challenge?<Field label="Username or email"><Input required maxLength={160} autoComplete="username" value={identity} onChange={e=>setIdentity(e.target.value)}/></Field>:<><p>{challenge.message}</p><Field label="Six-digit code"><Input required pattern="[0-9]{6}" inputMode="numeric" autoComplete="one-time-code" value={code} maxLength={6} onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/></Field><Field label="New password"><Input required minLength={10} maxLength={72} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></Field><Field label="Repeat password"><Input required type="password" autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></Field></>}{error&&<p role="alert" className="fm-error">{error}</p>}<Button disabled={busy}>{busy?"Please wait...":challenge?"Reset password":"Send recovery code"}</Button>{challenge&&<Button type="button" variant="ghost" disabled={busy} onClick={()=>{setChallenge(undefined);setCode("");}}>Request another code</Button>}</form>}</DialogContent></Dialog>;
}
